package br.com.maratonajava.aula.Aprojetos.estoque.types;

public enum Brand {
    // ELETRODOMESTICOS
    LG, SAMSUNG, BOSCH, WHIRLPOOL,

    // ELETRONICOS
    SONY, SAMSUNG_ELECTRONICS, MICROSOFT, DELL, HP, LENOVO, ASUS, ACER, IPHONE, XIAOMI,

    // ROUPAS_ESPORTIVAS
    NIKE, ADIDAS, PUMA, REEBOK, UNDER_ARMOUR,

    // BEBIDAS
    COCA_COLA, PEPSI, RED_BULL, DR_PEPPER,

    // BRINQUEDOS
    LEGO, MATTEL, HASBRO, FISHER_PRICE,

    // CONSOLES_DE_VIDEOGAME
    SONY_PLAYSTATION, MICROSOFT_XBOX, NINTENDO_SWITCH
}
